//Creado por Sebastian Garita, favor ignorar es para hacer pruebas de los end points, funciona como postman pero me va mejor aca

GET http://localhost:3000/api/listar-clientes

###

POST http://localhost:3000/api/registrar-producto
Content-Type: application/json

{
  
        
            "cedula_vendedor": "12345",
            "nombre": "Producto 1",
            "tramo": "Tramo Test",
            "descripcion": "Descripción del Producto 1",
            "categoria": "Lacteos",
            "imagen": "imagen1.jpg",
            "precio_vendedor": "15.99",
            "inventario": "10"
        
   
}



###

GET http://localhost:3000/api/listar-ventas-cedula?cedula=509870789
Content-Type: application/json

###

GET http://localhost:3000/api/listar-frutas-verduras
Content-Type: application/json

###

GET http://localhost:3000/api/listar-producto-por-id
Content-Type: application/json

{
  "id": "661b076bd0c1bfad53b755e8"
}

