//Creado por Sebastian Garita, favor ignorar es para hacer pruebas de los end points, funciona como postman pero me va mejor aca

GET http://localhost:3000/api/listar-clientes

###

PUT  http://localhost:3000/api/restablecer-inventario-producto
Content-Type: application/json

{
  
        
           
    "_id": "66357eddd4bde2515743e424",
    "cantidadNueva": "5"

        
   
}



###

GET http://localhost:3000/api/listar-ventas-cedula?cedula=509870789
Content-Type: application/json

###

GET http://localhost:3000/api/listar-frutas-verduras
Content-Type: application/json

###

GET http://localhost:3000/api/listar-producto-por-id
Content-Type: application/json

{
  "id": "661b076bd0c1bfad53b755e8"
}

